[pytest]
testpaths = task_2_1_api task_2_2_ui
addopts = -v --tb=short
markers =
    positive: позитивные тест-кейсы
    negative: негативные тест-кейсы
    corner: корнер-кейсы
    e2e: end-to-end тесты
    nonfunctional: нефункциональные тесты
    desktop: десктопные UI тесты
    mobile: мобильные UI тесты
